# Generated by Django 3.2.12 on 2022-09-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nback_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='colored_grid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='distraction',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='rotate',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sounds',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
