# Generated by Django 3.2.12 on 2022-09-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nback_app', '0005_alter_userdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='box_interval',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userdata',
            name='distraction_interval',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='userdata',
            name='place_letter',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='userdata',
            name='sound_letter',
            field=models.CharField(default='L', max_length=1),
        ),
    ]
