# Generated by Django 3.2.12 on 2022-09-28 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nback_app', '0006_auto_20220925_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='result',
            name='right_answers',
        ),
        migrations.RemoveField(
            model_name='result',
            name='total_nbacks',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='results',
        ),
        migrations.AddField(
            model_name='result',
            name='game_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='result',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nback_app.userdata'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='distraction_interval',
            field=models.IntegerField(default=5),
        ),
    ]
