# Generated by Django 3.2.12 on 2022-09-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nback_app', '0007_auto_20220928_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='difficulty_score',
            field=models.IntegerField(default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='result',
            name='right_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='total_nbacks',
            field=models.IntegerField(default=0),
        ),
    ]
