# Generated by Django 3.2.12 on 2022-10-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nback_app', '0009_userdata_rotate3d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='distraction_interval',
            field=models.IntegerField(default=1),
        ),
    ]
