# Generated by Django 3.2.12 on 2022-10-08 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nback_app', '0011_userdata_audio_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='nbacks',
            field=models.IntegerField(default=2, max_length=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='rotation_speed',
            field=models.FloatField(default=0.2, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='sequence_length',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(40)]),
        ),
    ]
