# Generated by Django 3.2.12 on 2022-10-08 07:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nback_app', '0012_auto_20221008_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='audio_volume',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
