# Generated by Django 3.2.12 on 2022-10-22 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nback_app', '0014_alter_userdata_audio_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='nbacks',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='audio_volume',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='box_interval',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='distraction_interval',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='rotation_speed',
            field=models.FloatField(default=0.2, validators=[django.core.validators.MinValueValidator(-3.0), django.core.validators.MaxValueValidator(3.0)]),
        ),
    ]
